name: CI/CD Web App & Prisma Migrations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image for testing
        run: docker build -f nextjs/Dockerfile.test -t traduxo-app:test .

      - name: Run unit tests inside container
        run: |
          docker run --rm traduxo-app:test

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v2
        
      - name: Build and push multi-arch image
        run: |
          docker buildx build \
            --platform linux/arm64,linux/amd64 \
            -f nextjs/Dockerfile.prod \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/traduxo-app:latest \
            --push .

      - name: SSH deploy to server with backup and safe migration
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /srv/traduxo

            # Backup current container as fallback
            docker tag traduxo-app:latest traduxo-app:backup

            # Pull new image
            docker compose pull

            # Run migrations in a temporary container first
            if docker compose run --rm app npx prisma migrate deploy; then
                # If migrations succeed, bring up new version
                docker compose up -d
            else
                # Rollback if migration fails
                echo "Migrations failed! Rolling back..."
                docker stop traduxo-app
                docker rm traduxo-app || true
                docker run -d --name traduxo-app traduxo-app:backup
                exit 1
            fi
